In [17]:
import numpy as np
print("=====ARRAY CREATION=====")
arr1 = np.array([1,2,3,4,5])
print("1D Array:",arr1)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D Array:",arr2)
print("=====ARRAY ATTRIBUTES=====")
print(f"arr1 shape: {arr1.shape}, arr2 shape: {arr2.shape}")
print(f"arr1 dimension: {arr1.ndim}, arr2 dimension: {arr2.ndim}")
print(f"arr1 total elements: {arr1.size}, arr2 total elements: {arr2.size}")
print(f"arr1 data type: {arr1.dtype}, arr2 data type: {arr2.dtype}")
print("=====INDEXING AND SLICING=====")
print(f"arr1 first element: {arr1[0]}, arr2 first element: {arr2[0]}")
print(f"arr1 last element: {arr1[-1]}, arr2 last element: {arr2[-1]}")
print(f"arr1 slice[1:3]:{arr1[1:3]}, arr2 slice[1:2]: {arr2[1:2]}")
print(f"reversed arr1: {arr1[::-1]}, reversed arr2: {arr2[::-1]}")
print("=====RESHAPING ARRAY=====")
print(f"arr1 shape to 5,1:{arr1.reshape(5,1)},\n arr2 reshape to 5,2: {arr2.reshape(5,2)}")


=====ARRAY CREATION=====
1D Array: [1 2 3 4 5]
2D Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
=====ARRAY ATTRIBUTES=====
arr1 shape: (5,), arr2 shape: (2, 5)
arr1 dimension: 1, arr2 dimension: 2
arr1 total elements: 5, arr2 total elements: 10
arr1 data type: int64, arr2 data type: int64
=====INDEXING AND SLICING=====
arr1 first element: 1, arr2 first element: [1 2 3 4 5]
arr1 last element: 5, arr2 last element: [ 6  7  8  9 10]
arr1 slice[1:3]:[2 3], arr2 slice[1:2]: [[ 6  7  8  9 10]]
reversed arr1: [5 4 3 2 1], reversed arr2: [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
=====RESHAPING ARRAY=====
arr1 shape to 5*1:[[1]
 [2]
 [3]
 [4]
 [5]],
 arr2 reshape to 5,2: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [4]:
print("\n----- 2. ARRAY ATTRIBUTES -----")
 
sample = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", sample)
print("Shape:", sample.shape)
print("Number of dimensions:", sample.ndim)
print("Size (total elements):", sample.size)
print("Data type:", sample.dtype)
print("Item size (bytes):", sample.itemsize)


----- 2. ARRAY ATTRIBUTES -----
Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (total elements): 6
Data type: int64
Item size (bytes): 8
